clone_depth: 1


environment:

  Solution: pkg\msvc\RetroArch-msvc2017.sln
  Configuration: Release


  matrix:
    - Platform: x86
    # - Platform: x64


artifacts:
  - path: '**\*Retroarch*.exe'



build_script:

  - cmd: msbuild "%SOLUTION%" /p:Configuration="%CONFIGURATION" /p:Platform="%PLATFORM" /m
